name: Minimal Android CI Workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Decode Keystore
        id: decode_keystore
        uses: timheuer/base64-to-file@v1.1
        with:
          fileDir: './secrets'
          fileName: 'console-app-keystore.jks'
          encodedString: ${{ secrets.KEYSTORE_FILE }}

      # Decode the Google Play api key file
      - name: Decode Google Play API key
        id: decode_api_key
        uses: timheuer/base64-to-file@v1.1
        with:
          fileDir: './secrets'
          fileName: 'google-play-api-key.json'
          encodedString: ${{ secrets.GOOGLE_PLAY_API_KEY }}
      - name: add secret
        run: |
          cat > keystore.properties << ENDOFFILE
          KEYSTORE_FILE=${{steps.decode_keystore.outputs.filePath}}
          GOOGLE_PLAY_API_KEY=../${{steps.decode_api_key.outputs.filePath}}
          KEY_ALIAS=${{secrets.KEY_ALIAS}}
          KEY_PASSWORD=${{secrets.KEY_PASSWORD}}
          KEYSTORE_PASSWORD=${{secrets.KEYSTORE_PASSWORD}}
          ENDOFFILE

      - name: Build Project
        run: ./gradlew build

