name: CI/CD Google Play 3

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Decode Keystore
        id: decode_keystore
        uses: timheuer/base64-to-file@v1
        with:
          fileName: 'console-app-keystore.jks'
          encodedString: ${{ secrets.KEYSTORE_FILE }}
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: build prod
        run: ./gradlew app:bundleRelease
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: Build Artifacts
          
