name: CI/CD Google Play

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle

      # Create a build number based on timestamp / UTC time
      - name: set release date
        run: |
          echo "BUILD_NUMBER=$(date +"%s")" >> ${GITHUB_ENV}
      # Decode the keystore file containing the signing key
      - name: Decode Keystore
        id: decode_keystore
        uses: timheuer/base64-to-file@v1.1
        with:
          fileDir: './secrets'
          fileName: 'console-app-keystore.jks'
          encodedString: ${{ secrets.KEYSTORE_FILE }}

      # Decode the Google Play api key file
      - name: Decode Google Play API key
        id: decode_api_key
        uses: timheuer/base64-to-file@v1.1
        with:
          fileDir: './secrets'
          fileName: 'google-play-api-key.json'
          encodedString: ${{ secrets.GOOGLE_PLAY_API_KEY }}
      - name: add secret
        run: |
          cat > keystore.properties << ENDOFFILE
          KEYSTORE_FILE=${{steps.decode_keystore.outputs.filePath}}
          ENDOFFILE

      # Build bundle and publish to Google Play
      - name: Build & publish to Google Play
        run: ./gradlew
          -PBUILD_NUMBER="${{ env.BUILD_NUMBER }}"
          -PgooglePlayApiKey="../${{ steps.decode_api_key.outputs.filePath }}"
          -PKEYSTORE_FILE="${{ steps.decode_keystore.outputs.filePath }}"
          -PKEYSTORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }}
          -PKEY_ALIAS=${{ secrets.KEY_ALIAS }}
          -PKEY_PASSWORD=${{ secrets.KEY_PASSWORD }}
          publishProdReleaseBundle --max-workers 1 --stacktrace
