name: CI/CD Google Play 2

on: workflow_dispatch

jobs:

  buildApk:
    runs-on: ubuntu-latest
    
    steps:
     
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle
          
      - name: Add secrets
        run: |
          cat > keystore.properties << ENDOFFILE
            storeFile=${{secrets.KEYSTORE_FILE_PATH}}
          ENDOFFILE
          
      - name: build APK
        run: ./gradlew :app:assembleProd
      - name: Sign Android release
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: console/app/build/outputs/apk/prod/release
          signingKeyBase64: ${{secrets.KEYSTORE_FILE}}
          alias: ${{secrets.KEY_ALIAS}}
          keyStorePassword: ${{secrets.KEYSTORE_PASSWORD}}
          keyPassword: ${{secrets.KEY_PASSWORD}}

      - name: Upload app APK as artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release
          path: ${{env.SIGNED_RELEASE_FILE}}


