name: CI/CD Google Play 2

on: workflow_dispatch

jobs:

  buildApk:
    runs-on: ubuntu-latest
    steps:
      - name: build APK
        run: ./gradlew assembleProdRelease
      - name: Sign Android release
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: console/app/build/outputs/apk/prod/release
          signingKeyBase64: ${{secrets.KEYSTORE_FILE}}
          alias: ${{secrets.KEY_ALIAS}}
          keyStorePassword: ${{secrets.KEYSTORE_PASSWORD}}
          keyPassword: ${{secrets.KEY_PASSWORD}}

      - name: Upload app APK as artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release
          path: ${{env.SIGNED_RELEASE_FILE}}


